version: "3"

services:
  babelfishpg-ubuntu-focal:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu-focal
      args:
        buildno: 1
        MAX_JOBS: 4
    image: babelfishpg:ubuntu.focal
    ports:
      - 1433:10433
      - 5432:15432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - BABELFISH_USER=bbf
      - BABELFISH_PASS=password
      - BABELFISH_DB=bbf
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - babelfish

networks:
  babelfish:
      